# Generated by Django 2.0.2 on 2018-11-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrifoma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
