# Generated by Django 2.0 on 2018-11-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('A', 'Electric Installation'), ('B', 'Laundry'), ('C', 'House Cleaning'), ('D', 'Shopping and Delievery'), ('E', 'Handy Work'), ('F', 'Garden Work'), ('G', 'Interior Painting'), ('H', 'Painting'), ('I', 'Catering'), ('J', 'Helping Carry'), ('K', 'Transportation and Delivery')], max_length=1)),
            ],
        ),
    ]
