# Generated by Django 2.0 on 2018-11-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, choices=[('A', 'Electric Installation'), ('B', 'Laundry'), ('C', 'House Cleaning'), ('D', 'Shopping and Delievery'), ('E', 'Handy Work'), ('F', 'Garden Work'), ('G', 'Interior Painting'), ('H', 'Painting'), ('I', 'Catering'), ('J', 'Helping Carry'), ('K', 'Transportation and Delivery')], max_length=1),
        ),
    ]
