# Generated by Django 2.0.2 on 2018-11-14 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_provider_ratingcompany_ratingprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.Company'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service',
            field=models.ManyToManyField(related_name='service', to='api.Service'),
        ),
    ]
